---
swagger: "2.0"
info:
  description: "The Allele Calling  service provides an API for converting raw sequence\
    \ data to GFE and HLA allele calls."
  version: "0.0.4"
  title: "Allele Calling Service"
  contact:
    email: "mhalagan@nmdp.org"
  license:
    name: "GNU GENERAL PUBLIC LICENSE"
    url: "https://www.gnu.org/licenses/lgpl.html"
paths:
  /ard:
    get:
      description: "Get HLA and GFE from consensus sequence or GFE notation"
      operationId: "ard_get"
      produces:
      - "application/json"
      parameters:
      - name: "glstring"
        in: "query"
        description: "Valid glstring"
        required: true
        type: "string"
      - name: "dbversion"
        in: "query"
        description: "URL for the neo4j graph"
        required: false
        type: "string"
      - name: "ard_type"
        in: "query"
        description: "ARD Type"
        required: false
        type: "string"
      - name: "verbose"
        in: "query"
        description: "Flag for running service in verbose"
        required: false
        type: "boolean"
      responses:
        200:
          description: "HLA and GFE from consensus sequence"
          schema:
            $ref: "#/definitions/Glstring"
        404:
          description: "Failed to generate GFE"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Error:
    type: "object"
    required:
    - "Message"
    - "version"
    properties:
      Message:
        type: "string"
      version:
        type: "string"
  Glstring:
    type: "object"
    properties:
      glstring:
        type: "string"
    example:
      glstring: "novel"
